version: '3.7'

services:
  web-dev:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - game-communication-gateway
    volumes:
      - "/app/node_modules"
      - "./:/app"
  web-prod:
    container_name: my-app-prod
    build: .
    ports:
      - '1337:80'
    networks:
      - game-communication-gateway
networks:
  game-communication-gateway:
    external: true
